"""add moisture

Revision ID: 0cc394ef57a4
Revises: 8d8e2b47d82d
Create Date: 2025-07-12 19:56:37.906667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cc394ef57a4'
down_revision: Union[str, Sequence[str], None] = '8d8e2b47d82d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moisture_sensor_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('moisture_level', sa.Integer(), nullable=False),
    sa.Column('moisture_percentage', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moisture_sensor_data')
    # ### end Alembic commands ###
